version: 1.0.0

services:
  app:
    image: my-node-app
    build:
      context: .
    volumes:
      - ./src:/app/src
      - ./:/app
      - ./node_modules:/app/node_modules
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    